identifier: "lipschitz_monotonic" # Identifier for the model configuration for logging and bookeeping

# hidden layer dimensions
layer_dims: [128, 128, 128, 128, 128, 128, 128]

# Lipschitz-specific parameters
activation_fn: "groupsort"
lip_const: 2.0
nbody: "ThreeBody"
monotonic: true  # Flag to enforce monotonicity constraints
lip_kind: "nominal" # Options: "nominal", "default", "one"

# Regular parameters
dropout_rate: 0.0
batch_norm: false
l1_factor: 0.0
residual: false
init_method: "xavier_uniform"