identifier: "lipschitz_monotonic" # Identifier for the model configuration for logging and bookeeping

# hidden layer dimensions
layer_dims: [32, 64, 128, 64, 32]

# Lipschitz-specific parameters
activation_fn: "groupsort"
lip_const: 2.0
nbody: "TwoBody"
monotonic: true  # Flag to enforce monotonicity constraints

# Regular parameters
dropout_rate: 0.0
batch_norm: false
l1_factor: 0.0
residual: false
init_method: "xavier_uniform"