identifier: "lipschitz_legacy"  

# Lipschitz-specific parameters
activation_fn: "groupsort"
lip_const: 2.0
nbody: "TwoBody"
monotonic: True  # Flag to enforce monotonicity constraints

# Regular parameters (these won't affect the architecture but are needed for config)
dropout_rate: 0.0
batch_norm: false
l1_factor: 0.0