identifier: "unconstrained_enhanced" # Identifier for the model configuration for logging and bookeeping

# Enhanced model configuration
model:
  # hidden layer dimensions
  layer_dims: [128, 128, 128, 128, 128, 128, 128] 
  
  # Regularization
  dropout_rate: 0.2
  batch_norm: true
  l1_factor: 0.01
  weight_decay: 1e-4
  
  # Architecture features
  residual: false
  activation_fn: "relu"
  init_method: "xavier_uniform"
  
  # Advanced options
  layer_specific:
    - idx: 0
      dropout_rate: 0.1
      batch_norm: true
    - idx: 1
      dropout_rate: 0.2
      batch_norm: true
    - idx: 2
      dropout_rate: 0.3
      batch_norm: true
    - idx: 3
      dropout_rate: 0.2
      batch_norm: true
    - idx: 4
      dropout_rate: 0.1
      batch_norm: true

  # Weight initialization ranges
  init_ranges:
    xavier_uniform:
      gain: 1.0
    xavier_normal:
      gain: 1.0
    kaiming_uniform:
      mode: "fan_in"
      nonlinearity: "relu"
    kaiming_normal:
      mode: "fan_out"
      nonlinearity: "relu"
    orthogonal:
      gain: 1.0