# MLflow configuration
mlflow:
  experiment_name: "performance_plots_mc_100epochs"
  tracking_uri: "http://localhost:5000"  # Update with your MLflow server
  tags:
    project: "TopoNBody Training [inclusive B]"
    version: "1.0"

# simple config
# -------------
# Architecture selection - options:
# - "unconstrained": Regular neural network (default or enhanced versions)
# - "unconstrained_enhanced": Enhanced regular neural network with advanced options
# - "lipschitz": Lipschitz-constrained neural network
# - "lipschitz_monotonic": Lipschitz-constrained neural network with monotonicity constraints
defaults:
  - model: lipschitz_monotonic
  - optimizer: adam 
  - _self_

# Path to features configuration file (with monotonicity constraints)
trigger: TwoBody
features_config_path: "config/features.yml"

# Metrics configuration
metrics:
  threshold: 0.5
  compute:
    loss: true
    roc_auc: true
    accuracy: true
    precision: true
    recall: true
    f1: true

# Training parameters
training:
  training_data_scale_factor: 1.0 # default: 1; full minimum bias
  sb_ratio: 25 # default: 1 - more physically correct (training and test have S>>B!) and yielding better training stability; evaluation on per-channel basis in terms of effs confirms this. In the limit of high stats, preferable
  num_epochs: 25
  batch_size: 128
  loss_fn: "bce_with_logits" # Options: bce_with_logits, focal, combined_focal_wbce, weighted_bce
  apply_preprocessing: True
  balance_train_sample: False # Nominal: False; very hard to calibrate both in physics and in delivering sensible training results

scheduler:
  name: "reduce_on_plateau"
  mode: "min"  # minimize the loss
  factor: 0.5  # Reduces learning rate by half when triggered
  patience: 10  # Number of epochs with no improvement before reducing LR
  min_lr: 1e-8  # Minimum learning rate

# Data paths
paths:
  # 2025 tuning samples
  train_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_2025/scratch/TwoBody_2025_IMbalanced/train.pkl" # no preprocessing from data pipeline; handles by DataModule here()
  test_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_2025/scratch/TwoBody_2025_IMbalanced/test.pkl" # idem=
  model_save_dir: "./models"
