# MLflow configuration
mlflow:
  experiment_name: "ltime_ipchi2_selected"
  tracking_uri: "http://localhost:5000"  # Update with your MLflow server
  tags:
    project: "TopoNBody Training [inclusive B]"
    version: "1.0"

# simple config
# -------------
# Architecture selection - options:
# - "unconstrained": Regular neural network (default or enhanced versions)
# - "unconstrained_enhanced": Enhanced regular neural network with advanced options
# - "lipschitz": Lipschitz-constrained neural network
# - "lipschitz_monotonic": Lipschitz-constrained neural network with monotonicity constraints
defaults:
  - model: lipschitz_monotonic #lipschitz_monotonic
  - optimizer: adam 
  - _self_

# Path to features configuration file (with monotonicity constraints)
trigger: ThreeBody # NOTE: CHANGE ALSO IN PATHS MODEL YAML FILE
features_config_path: "config/features.yml"

# Metrics configuration
metrics:
  threshold: 0.5
  compute:
    loss: true
    roc_auc: true
    accuracy: true
    precision: true
    recall: true
    f1: true

# Training parameters
training:
  training_data_scale_factor: 0.1 # default: 1; full minimum bias 
  sb_ratio: 1.0 # default: 1 - more physically correct (training and test have S>>B!) and yielding better training stability; evaluation on per-channel basis in terms of effs confirms this. In the limit of high stats, preferable
  num_epochs: 30
  batch_size: 128
  loss_fn: "disco" # Options: bce_with_logits, focal, combined_focal_wbce, weighted_bce, disco, conditional_disco
  lambda_disco: 1.0 # default: 1.0; trade-off between BCE and DisCo loss
  include_spectators: True # default: True; whether to include spectators in the loss function
  apply_preprocessing: True
  balance_train_sample: False # Nominal: False; very hard to calibrate both in physics and in delivering sensible training results

scheduler:
  name: "reduce_on_plateau"
  mode: "min"  # minimize the loss
  factor: 0.5  # Reduces learning rate by half when triggered
  patience: 10  # Number of epochs with no improvement before reducing LR
  min_lr: 1e-8  # Minimum learning rate

# Data paths
paths:
  # 2025 tuning samples
  # train_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp/scratch/TwoBody/imbalanced/train.pkl" # no preprocessing from data pipeline; handles by DataModule here()
  # test_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp/scratch/TwoBody/imbalanced/test.pkl" # idem=
  
  # train_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_maxstats/scratch/TwoBody/imbalanced/train.pkl" # no preprocessing from data pipeline; handles by DataModule here()
  # test_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_maxstats/scratch/TwoBody/imbalanced/test.pkl" # idem=

  #train_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_maxstats/scratch/TwoBody/imbalanced/train_ltime_ipchi2_selected.pkl" # no preprocessing from data pipeline; handles by DataModule here()
  #test_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_maxstats/scratch/TwoBody/imbalanced/test_ltime_ipchi2_selected.pkl" # idem=

  #train_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp/scratch/ThreeBody/imbalanced/train.pkl" # no preprocessing from data pipeline; handles by DataModule here()
  #test_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp/scratch/ThreeBody/imbalanced/test.pkl" # 

  train_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_maxstats/scratch/ThreeBody/imbalanced/train.pkl" # no preprocessing from data pipeline; handles by DataModule here()
  test_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_maxstats/scratch/ThreeBody/imbalanced/test.pkl" # idem=

  # train_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_maxstats/scratch/ThreeBody/imbalanced/train.pkl" # no preprocessing from data pipeline; handles by DataModule here()
  # test_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp_maxstats/scratch/ThreeBody/imbalanced/test.pkl" # idem=

  #train_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp/scratch/ThreeBody/imbalanced/train_dev.pkl" # no preprocessing from data pipeline; handles by DataModule here()
  #test_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp/scratch/ThreeBody/imbalanced/test_dev.pkl" # idem=
  

  model_save_dir: "./models"
