# MLflow configuration
mlflow:
  experiment_name: "lhcb_run3_topo_2body_classification_2024_tuning"
  tracking_uri: "http://localhost:5000"  # Update with your MLflow server
  tags:
    project: "Topo2Body Training"
    version: "1.0"

# simple config
# -------------
# Architecture selection - options:
# - "unconstrained": Regular neural network (default or enhanced versions)
# - "unconstrained_enhanced": Enhanced regular neural network with advanced options
# - "lipschitz": Lipschitz-constrained neural network
# - "lipschitz_monotonic": Lipschitz-constrained neural network with monotonicity constraints
defaults:
  - model: lipschitz_monotonic
  - optimizer: adam 
  - _self_

# Path to features configuration file (with monotonicity constraints)
trigger: TwoBody
features_config_path: "config/features.yml"

# Metrics configuration
metrics:
  threshold: 0.5
  compute:
    loss: true
    roc_auc: true
    accuracy: true
    precision: true
    recall: true
    f1: true

# Training parameters
training:
  training_data_scale_factor: 1
  sb_ratio: ~
  num_epochs: 50
  batch_size: 128
  loss_fn: "bce_with_logits" # Options: bce_with_logits, focal, combined_focal_wbce, weighted_bce

# Data paths
paths:
  train_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp/scratch/TwoBody/preprocessed/train.pkl"
  test_data: "/ceph/submit/data/user/b/blaised/hlt2topo_sp/scratch/TwoBody/preprocessed/test.pkl"
  model_save_dir: "./models"
