# feature list : monotonic constraint
features:
  TwoBody:
    min_PT_final_state_tracks: 1
    sum_PT_final_state_tracks: 0 # 1
    min_FS_OWNPVIPCHI2: 1
    max_FS_OWNPVIPCHI2: 0
    TwoBody_PT: 0
    TwoBody_MAXDOCA: 0
    TwoBody_OWNPVCORRM: 0
    TwoBody_OWNPVFDCHI2: 0
    TwoBody_ENDVERTEX_CHI2DOF: 0

  ThreeBody:
    min_FS_IPCHI2_OWNPV: 1
    max_FS_IPCHI2_OWNPV: 0
    sum_PT_TRACK12: 1
    min_PT_TRACK12: 1
    sum_PT_final_state_tracks: 1
    min_PT_final_state_tracks: 1
    TwoBody_DOCAMAX: 0
    ThreeBody_DOCAMAX: 0
    TwoBody_FDCHI2_OWNPV: 0
    TwoBody_IPCHI2_OWNPV: 0
    ThreeBody_FDCHI2_OWNPV: 0
    ThreeBody_PT: 1
    TwoBody_PT: 1
    TwoBody_ENDVERTEX_CHI2DOF: 0
    ThreeBody_ENDVERTEX_CHI2DOF: 0
    ThreeBody_MCORR: 0
    TwoBody_MCORR: 0

transforms: # preprocessing: transfrom -> quantile-based clipping -> normalisation
  TwoBody:
    min_PT_final_state_tracks: "gev"
    sum_PT_final_state_tracks: "gev"
    min_FS_IPCHI2_OWNPV: "log"
    max_FS_IPCHI2_OWNPV: "log"
    TwoBody_PT: "gev"
    TwoBody_DOCAMAX: ~
    TwoBody_MCORR: "gev"
    TwoBody_FDCHI2_OWNPV: "log"
    TwoBody_ENDVERTEX_CHI2DOF: "log"